# Generated by Django 3.1.6 on 2021-02-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=100)),
                ('cus_doc_number', models.CharField(max_length=14)),
                ('cus_phone', models.CharField(max_length=20)),
                ('cus_email', models.EmailField(max_length=50)),
                ('cus_gender', models.CharField(choices=[('NON-BINARY', 'Non-binary'), ('TRANSGENDER', 'Trangender'), ('GENDER NEUTRAL', 'Gender neutral'), ('CISGENDER', 'Cisgender')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=100)),
                ('sport_modality', models.CharField(choices=[('VOLLEY', 'Volley'), ('FOOTBALL', 'Football'), ('RACES', 'Races'), ('FIGHT', 'Fight'), ('SOCCER', 'Soccer')], max_length=100)),
                ('bet_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_sport', models.ManyToManyField(to='core.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_description', models.TextField(max_length=255, null=True)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_category', models.ManyToManyField(to='core.Category')),
            ],
        ),
    ]
