# Generated by Django 3.1.6 on 2021-02-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_gender',
            field=models.CharField(choices=[('GENDER NEUTRAL', 'Gender neutral'), ('CISGENDER', 'Cisgender'), ('TRANSGENDER', 'Trangender'), ('NON-BINARY', 'Non-binary')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sport_modality',
            field=models.CharField(choices=[('VOLLEY', 'Volley'), ('SOCCER', 'Soccer'), ('FIGHT', 'Fight'), ('RACES', 'Races'), ('FOOTBALL', 'Football')], max_length=100),
        ),
    ]
