# Generated by Django 3.1.6 on 2021-02-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210211_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sport_modality',
            field=models.CharField(max_length=100),
        ),
    ]
