# Generated by Django 3.1.6 on 2021-02-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210211_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cus_doc_number',
            new_name='customer_doc_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cus_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cus_gender',
            new_name='customer_gender',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cus_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cus_phone',
            new_name='customer_phone',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_price',
            new_name='product_price',
        ),
    ]
